namespace MCW10StatsViewer {

    public enum EntityRenderModel : int
    {
        None,
        Reserved_1,
        Primed_Tnt,
        Humanoid_Mob,
        Item,
        Chicken,
        Cow,
        Mushroom_Cow,
        Pig,
        Sheep,
        Bat,
        Wolf,
        Villager,
        Reserved_13,
        Zombie,
        Pig_Zombie,
        Lava_Slime,
        Ghast,
        Blaze,
        Skeleton,
        Spider,
        Silverfish,
        Creeper,
        Slime,
        Enderman,
        Arrow,
        Fish_Hook,
        Player,
        Item_Sprite_28,
        Item_Sprite_29,
        Item_Sprite_30,
        Thrown_Potion,
        Painting,
        Falling_Block,
        Minecart,
        Boat,
        Squid,
        Large_Fireball,
        Small_Fireball,
        Zombie_Villager,
        Experience_Orb,
        Lightning_Bolt,
        Iron_Golem,
        Ocelot,
        Snow_Golem,
        Item_Sprite_45,
        Rabbit,
        Witch,
        Horse,
        Tripod_Camera,
        Reserved_50,
        Map,
        Leash_Knot,
        Reserved_53,
        Husk,
        Stray
    }

    public enum DataValue : short {
        air = 0,
        stone = 1,
        grass = 2,
        dirt = 3,
        cobblestone = 4,
        planks = 5,
        sapling = 6,
        bedrock = 7,
        flowing_water = 8,
        water = 9,
        flowing_lava = 10,
        lava = 11,
        sand = 12,
        gravel = 13,
        gold_ore = 14,
        iron_ore = 15,
        coal_ore = 16,
        log = 17,
        leaves = 18,
        sponge_dry = 19,
        glass = 20,
        lapis_ore = 21,
        lapis_block = 22,
        dispenser = 23,
        sandstone = 24,
        noteblock = 25,
        bed = 26,
        golden_rail = 27,
        detector_rail = 28,
        sticky_piston = 29,
        web = 30,
        tall_grass = 31,
        dead_bush = 32,
        piston = 33,
        piston_Arm_Collision = 34,
        wool = 35,
        yellow_flower = 37,
        red_flower = 38,
        brown_mushroom = 39,
        red_mushroom = 40,
        gold_block = 41,
        iron_block = 42,
        double_stone_slab = 43,
        stone_slab = 44,
        brick_block = 45,
        tnt = 46,
        bookshelf = 47,
        mossy_cobblestone = 48,
        obsidian = 49,
        torch = 50,
        fire = 51,
        mob_spawner = 52,
        oak_stairs = 53,
        chest = 54,
        redstone_wire = 55,
        diamond_ore = 56,
        diamond_block = 57,
        crafting_table = 58,
        wheat = 59,
        farmland = 60,
        furnace = 61,
        lit_furnace = 62,
        standing_sign = 63,
        wooden_door = 64,
        ladder = 65,
        rail = 66,
        stone_stairs = 67,
        wall_sign = 68,
        lever = 69,
        stone_pressure_plate = 70,
        iron_door = 71,
        wooden_pressure_plate = 72,
        redstone_ore = 73,
        lit_redstone_ore = 74,
        unlit_redstone_torch = 75,
        redstone_torch = 76,
        stone_button = 77,
        snow_layer = 78,
        ice = 79,
        snow = 80,
        cactus = 81,
        clay = 82,
        reeds = 83,
        fence = 85,
        pumpkin = 86,
        netherrack = 87,
        soul_sand = 88,
        glowstone = 89,
        portal = 90,
        lit_pumpkin = 91,
        cake = 92,
        unpowered_repeater = 93,
        powered_repeater = 94,
        invisible_Bedrock = 95,
        trapdoor = 96,
        monster_egg = 97,
        stonebrick = 98,
        brown_mushroom_block = 99,
        red_mushroom_block = 100,
        iron_bars = 101,
        glass_pane = 102,
        melon_block = 103,
        pumpkin_stem = 104,
        melon_stem = 105,
        vine = 106,
        fence_gate = 107,
        brick_stairs = 108,
        stone_brick_stairs = 109,
        mycelium = 110,
        waterlily = 111,
        nether_brick = 112,
        nether_brick_fence = 113,
        nether_brick_stairs = 114,
        nether_wart = 115,
        enchanting_table = 116,
        brewing_stand = 117,
        cauldron = 118,
        end_portal_frame = 120,
        end_stone = 121,
        redstone_lamp = 123,
        lit_redstone_lamp = 124,
        dropper = 125,
        activator_rail = 126,
        cocoa = 127,
        sandstone_stairs = 128,
        emerald_ore = 129,
        tripwire_hook = 131,
        tripWire = 132,
        emerald_block = 133,
        spruce_stairs = 134,
        birch_stairs = 135,
        jungle_stairs = 136,
        cobblestone_wall = 139,
        flower_pot = 140,
        carrots = 141,
        potatoes = 142,
        wooden_button = 143,
        skull = 144,
        anvil = 145,
        trapped_chest = 146,
        light_weighted_pressure_plate = 147,
        heavy_weighted_pressure_plate = 148,
        unpowered_comparator = 149,
        powered_comparator = 150,
        daylight_detector = 151,
        redstone_block = 152,
        quartz_ore = 153,
        hopper = 154,
        quartz_block = 155,
        quartz_stairs = 156,
        double_wooden_slab = 157,
        wooden_slab = 158,
        stained_hardened_clay = 159,
        leaves2 = 161,
        log2 = 162,
        acacia_stairs = 163,
        dark_oak_stairs = 164,
        slime = 165,
        iron_trapdoor = 167,
        hay_block = 170,
        carpet = 171,
        hardened_clay = 172,
        coal_block = 173,
        packed_ice = 174,
        double_plant = 175,
        daylight_detector_inverted = 178,
        red_sandstone = 179,
        red_sandstone_stairs = 180,
        double_stone_slab2 = 181,
        stone_slab2 = 182,
        spruce_fence_gate = 183,
        birch_fence_gate = 184,
        jungle_fence_gate = 185,
        dark_oak_fence_gate = 186,
        acacia_fence_gate = 187,
        spruce_door = 193,
        birch_door = 194,
        jungle_door = 195,
        acacia_door = 196,
        dark_oak_door = 197,
        grass_path = 198,
        frame = 199,
        podzol = 243,
        beetroot = 244,
        stonecutter = 245,
        glowing_obsidian = 246,
        nether_reactor = 247,
        info_update = 248,
        info_update2 = 249,
        movingBlock = 250,
        observer = 251,
        reserved6 = 255,
        Shovel_iron = 256,
        PickAxe_iron = 257,
        Hatchet_iron = 258,
        Flint_And_Steel = 259,
        Apple = 260,
        Bow = 261,
        Arrow = 262,
        Coal = 263,
        Diamond = 264,
        IronIngot = 265,
        GoldIngot = 266,
        Sword_iron = 267,
        Sword_wood = 268,
        Shovel_wood = 269,
        PickAxe_wood = 270,
        Hatchet_wood = 271,
        Sword_stone = 272,
        Shovel_stone = 273,
        PickAxe_stone = 274,
        Hatchet_stone = 275,
        Sword_diamond = 276,
        Shovel_diamond = 277,
        PickAxe_diamond = 278,
        Hatchet_diamond = 279,
        Stick = 280,
        Bowl = 281,
        Mushroom_Stew = 282,
        Sword_gold = 283,
        Shovel_gold = 284,
        PickAxe_gold = 285,
        Hatchet_gold = 286,
        String = 287,
        Feather = 288,
        Sulphur = 289,
        Hoe_wood = 290,
        Hoe_stone = 291,
        Hoe_iron = 292,
        Hoe_diamond = 293,
        Hoe_gold = 294,
        Seeds_wheat = 295,
        Wheat = 296,
        Bread = 297,
        Helmet_cloth = 298,
        Chestplate_cloth = 299,
        Leggings_cloth = 300,
        Boots_cloth = 301,
        Helmet_chain = 302,
        Chestplate_chain = 303,
        Leggings_chain = 304,
        Boots_chain = 305,
        Helmet_iron = 306,
        Chestplate_iron = 307,
        Leggings_iron = 308,
        Boots_iron = 309,
        Helmet_diamond = 310,
        Chestplate_diamond = 311,
        Leggings_diamond = 312,
        Boots_diamond = 313,
        Helmet_gold = 314,
        Chestplate_gold = 315,
        Leggings_gold = 316,
        Boots_gold = 317,
        Flint = 318,
        PorkChop_raw = 319,
        PorkChop_cooked = 320,
        Painting = 321,
        Apple_gold = 322,
        Sign = 323,
        Door_wood = 324,
        Bucket = 325,
        Minecart = 328,
        Saddle = 329,
        Door_iron = 330,
        RedStone = 331,
        SnowBall = 332,
        Boat = 333,
        Leather = 334,
        Brick = 336,
        Clay = 337,
        Reeds = 338,
        Paper = 339,
        Book = 340,
        Slime_Ball = 341,
        Chest_Minecart = 342,
        Egg = 344,
        Compass = 345,
        Fishing_Rod = 346,
        Clock = 347,
        YellowDust = 348,
        Fish_raw_cod = 349,
        Fish_cooked_cod = 350,
        Dye_powder = 351,
        Bone = 352,
        Sugar = 353,
        Cake = 354,
        Bed = 355,
        Repeater = 356,
        Cookie = 357,
        Filled_Map = 358,
        Shears = 359,
        Melon = 360,
        Seeds_pumpkin = 361,
        Seeds_melon = 362,
        Beef_raw = 363,
        Beef_cooked = 364,
        Chicken_raw = 365,
        Chicken_cooked = 366,
        Rotten_flesh = 367,
        Blaze_Rod = 369,
        Ghast_tear = 370,
        Gold_nugget = 371,
        Nether_wart = 372,
        Potion = 373,
        Glass_bottle = 374,
        Spider_eye = 375,
        Fermented_spider_eye = 376,
        Blaze_Powder = 377,
        Magma_cream = 378,
        Brewing_stand = 379,
        Cauldron = 380,
        Speckled_melon = 382,
        Mob_Placer = 383,
        Experience_Potion_Item = 384,
        Fire_Charge = 385,
        Emerald = 388,
        Item_Frame = 389,
        Flower_Pot = 390,
        Carrot = 391,
        Potato = 392,
        Potato_Baked = 393,
        Poisonous_potato = 394,
        EmptyMap = 395,
        Golden_Carrot = 396,
        Skull = 397,
        Carrot_On_A_Stick = 398,
        Pumpkin_Pie = 400,
        Enchanted_book = 403,
        Comparator = 404,
        Netherbrick = 405,
        Nether_Quartz = 406,
        TNT_Minecart = 407,
        Hopper_Minecart = 408,
        Hopper = 410,
        Rabbit_Raw = 411,
        Rabbit_Cooked = 412,
        Rabbit_Stew = 413,
        Rabbit_Foot = 414,
        Rabbit_Hide = 415,
        Leather_Horse_Armor = 416,
        Iron_Horse_Armor = 417,
        Gold_Horse_Armor = 418,
        Diamond_Horse_Armor = 419,
        Lead = 420,
        Name_Tag = 421,
        Mutton_raw = 423,
        Mutton_cooked = 424,
        Door_spruce = 427,
        Door_birch = 428,
        Door_jungle = 429,
        Door_acacia = 430,
        Door_darkoak = 431,
        Splash_potion = 438,
        Beetroot = 457,
        Seeds_beetroot = 458,
        Beetroot_Soup = 459,
        Fish_raw_salmon = 460,
        Fish_raw_clownfish = 461,
        Fish_raw_pufferfish = 462,
        Fish_cooked_salmon = 463,
        Apple_enchanted = 466,
        Camera = 498
    }
}